sudo: 'required'
language: 'minimal'
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.24.1
before_install:
  - sudo apt-get update -y
  - sudo apt-get install docker-ce -y
  - sudo service docker restart
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
script:
  - docker version
  - docker-compose run vue-dev npm test # jest test with coverage flag does coverage too
after_script:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls' # sends the coverage report to coverall s 
