sudo: 'required'
language: 'minimal'
services:
  - docker
before_install:
  - sudo apt-get update -y
  - sudo apt-get install docker-ce -y
  - sudo service docker restart
script:
  - docker version
  - docker-compose run vue-dev npm test # jest test with coverage flag does coverage too
after_script:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls' # sends the coverage report to coverall s
