version: '3.7'
services:
  hhapp-front-dev:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: 'develop-stage'
    ports:
    - '8080:8080'
    tty: true
    volumes:
    - '.:/app'
    - '/app/node_modules' # Used to keep all modules inside container
    command: npm run serve